### PR TITLE
fix: remove leftover wallet lockfiles before startup

### LINKED ISSUE #38: Delete .lock files on startup
Most reported problem for dockerized Jam so far is that users are unable to unlock their wallet after, e.g. a power outage or other unclean shutdowns in general.

As suggested in https://github.com/getumbrel/umbrel-apps/pull/52#issuecomment-1171034380, let's evaluate if deleting all lockfiles (`.joinmarket/wallets/.*.lock`) is a proper workaround. This approach should be safe, as no service is running when `docker-entrypoint.sh` is invoked.

### PR DESCRIPTION
**Pull request by theborakompanioni**
Closes #38.

Mitigates unlock issues after unclean shutdowns by removing any existing lockfiles before startup.
Can be controlled by passing env var `REMOVE_LOCK_FILES`.

### CODE REVIEW

File: standalone/docker-entrypoint.sh [hunk 1]
```diff
@@ -16,6 +16,12 @@ if [ ! -f "$AUTO_START" ]; then
     cp "$DEFAULT_AUTO_START" "$AUTO_START"
 fi
 
+# remove leftover lockfiles from possible unclean shutdowns before startup
+if [ "${REMOVE_LOCK_FILES}" ] && [ "${REMOVE_LOCK_FILES}" != false ]; then
```
Comment (dnlggr) [inline standalone/docker-entrypoint.sh:20]: A couple lines above we only interpret a flag as set if it is explicitly `true`. Feels like the safer approach somehow or at least consistent with what we have (whitelist vs. blacklist).

**Review by dnlggr — APPROVED** [review]
